---
- name: Ensure NFS utilities are installed.
  package: name=nfs-utils state=present

- name: Ensure rpcbind is running as configured.
  service:
    name: rpcbind
    state: "{{ nfs_rpcbind_state }}"
    enabled: "{{ nfs_rpcbind_enabled }}"
- name: Open firewall ports
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  notify: "Restart firewalld"
  loop:
    - rpc-bind
    - mountd
    - nfs
  ignore_errors: True
